# Generated by Django 4.2 on 2023-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useractivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivationtoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
