from .authentication_tests import AuthenticationTest
from .register_tests import RegisterTests
from .register_signal_tests import RegisterSignalTests
from .password_creation_tests import PasswordCreationTests
