# Generated by Django 5.0 on 2023-12-10 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/home/spaces/default/default.jpg', upload_to='media/home/spaces')),
                ('title', models.CharField(default='Filmes, séries etc.', max_length=32)),
                ('objective', models.TextField(default='Assistir coisas legais')),
                ('is_private', models.BooleanField(default=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('partners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sem nome', max_length=64)),
                ('is_done', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.space')),
            ],
        ),
    ]
